#!/bin/bash
cd ~/Projects/erderkage
read -p "Commit description: " desc
git add . && \
git add -u && \
git commit -m "$desc" && \
git push origin master
node git-version.js
ng build --prod
cd ~/erderkagenu
rm public/*
mv ~/erderkage/dist/erderkage/* ~/erderkagenu/public/
git add . && \
git add -u && \
git commit -m "$desc" && \
git push heroku master
